=== pprados/macaron/trunk/audit/src/main/resources/com/googlecode/macaron/audit/audit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	* Copyright 2008 Philippe Prados.
	*
	* Licensed under the Apache License, Version 2.0 (the "License");
	* you may not use this file except in compliance with the License.
	* You may obtain a copy of the License at
	*
	*      http://www.apache.org/licenses/LICENSE-2.0
	*
	* Unless required by applicable law or agreed to in writing, software
	* distributed under the License is distributed on an "AS IS" BASIS,
	* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	* See the License for the specific language governing permissions and
	* limitations under the License.
	*

    $Id$
    $Log$
-->

<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://macaron.googlecode.com/1.0/"
	xmlns:tns="http://macaron.googlecode.com/1.0/"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="1.0">

	<element name="audit">
		<annotation>
			<documentation xml:lang="en">Backdoor audit report.</documentation>
			<documentation xml:lang="fr">Rapport d'audit de porte dérobée.</documentation>
		</annotation>
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:packages" />
				<element ref="tns:filenames" />
				<element ref="tns:basenames" />
				<element ref="tns:services" />
				<element ref="tns:comment" />
				<any processContents="strict" namespace="##other" />
			</choice>
			<attribute name="ignoreFilenames" type="string" use="optional" />
			<anyAttribute processContents="strict" />
		</complexType>
	</element>


	<element name="context">
		<complexType mixed="true" />
	</element>

	<element name="filenames">
		<complexType>
			<sequence>
				<element ref="tns:filename" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<element name="filename">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:context" />
				<element ref="tns:comment" />
				<any processContents="strict" namespace="##other" />
			</choice>
			<attribute name="name" type="string" use="required" />
		</complexType>
	</element>

	<element name="packages">
		<complexType>
			<sequence>
				<element ref="tns:package" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<element name="package">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:context" />
				<element ref="tns:comment" />
				<any processContents="strict" namespace="##other" />
			</choice>
			<attribute name="name" type="string" use="required" />
			<attribute name="sealed" type="boolean" use="optional" />
		</complexType>
	</element>

	<element name="basenames">
		<complexType>
			<sequence>
				<element ref="tns:basename" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<element name="basename">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:context" />
				<element ref="tns:comment" />
				<any processContents="strict" namespace="##other" />
			</choice>
			<attribute name="name" type="string" use="required" />
		</complexType>
	</element>

	<element name="services">
		<complexType>
			<sequence>
				<element ref="tns:service" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<element name="service">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:context" />
				<element ref="tns:comment" />
				<any processContents="strict" namespace="##other" />
			</choice>
			<attribute name="name" type="string" use="required" />
		</complexType>
	</element>

	<element name="comment" type="string" />


</schema>

=== pprados/macaron/audit/src/main/resources/com/googlecode/macaron/audit/ignore.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- 
	* Copyright 2008 Philippe Prados.
	*
	* Licensed under the Apache License, Version 2.0 (the "License");
	* you may not use this file except in compliance with the License.
	* You may obtain a copy of the License at
	*
	*      http://www.apache.org/licenses/LICENSE-2.0
	*
	* Unless required by applicable law or agreed to in writing, software
	* distributed under the License is distributed on an "AS IS" BASIS,
	* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	* See the License for the specific language governing permissions and
	* limitations under the License.
	*

    $Id$
    $Log$
-->
<?xml-stylesheet href="audit.xslt" type="text/xsl"?>

<audit 
	xmlns="http://macaron.googlecode.com/1.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 	xsi:schemaLocation="http://macaron.googlecode.com/1.0/ http://macaron.googlecode.com/svn/trunk/audit/src/main/resources/com/googlecode/macaron/audit/audit.xsd"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"	
	ignoreFilenames="^([^_]+_[a-z]{2}(_[A-Z]{2}(_[a-z]{1,3})?)?\.properties)|(.+\.(xsd|dtd|txt))$"
>
	<!-- Meme package, archives différentes -->
	<packages>
		<package name=""/>
		<package name="META-INF/"/>
		<package name="META-INF/services/"/>
	</packages>
	
	<!-- Meme noms, package différent -->
	<filenames>
		<filename name="MANIFEST.MF"/>
		<filename name="NOTICE"/>
		<filename name="NOTICE.txt"/>
		<filename name="LICENSE"/>
		<filename name="LICENSE.txt"/>
		<filename name="license.txt"/>
		<filename name="package.html"/>
		<filename name="overview.html"/>
		<filename name="INDEX.LIST"/>
		<filename name="jar.policy"/>
		<filename name="pom.xml"/>
		<filename name="pom.properties"/>
	</filenames>
	<!-- Même basename, même package -->
	<basenames>
		<basename name="META-INF/NOTICE"/>
		<basename name="META-INF/LICENSE"/>
	</basenames>
</audit>

=== pprados/macaron/trunk/samples/backdoor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet href="audit-to-xhtml.xslt" type="text/xsl"?>
<audit 
	xmlns="http://macaron.googlecode.com/1.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://macaron.googlecode.com/1.0/ http://macaron.googlecode.com/svn/trunk/audit/src/main/resources/com/googlecode/macaron/audit/audit.xsd"
	ignoreFilenames="^([^_]+_[a-z]{2}(_[A-Z]{2}(_[a-z]{1,3})?)?\.properties)|(.+\.(xsd|dtd|txt))$"
>

	<!-- Same package from differents jar. -->
	<packages/>

	<!-- Same name with differents package. -->
	<filenames>
		<filename name="aop.xml">
			<context>spring-aspects.jar!META-INF/</context>
			<context>petclinic.jar!META-INF/</context>
			<context>backdoor-1.0.jar!META-INF/</context>
		</filename>
	</filenames>

	<!-- Same basename with differents extensions in same package. -->
	<basenames>
		<basename name="messages">
			<context>backdoor-1.0.jar</context>
			<context>petclinic-with-backdoor.war</context>
		</basename>
	</basenames>

	<!-- Services in jar. -->
	<services>
		<service name="META-INF/services/javax.xml.parsers.SAXParserFactory">
			<context>backdoor-1.0.jar</context>
		</service>
		<service name="META-INF/services/javax.xml.parsers.DocumentBuilderFactory">
			<context>backdoor-1.0.jar</context>
		</service>
	</services>
</audit>

=== pprados/macaron/trunk/samples/tomcat.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet href="audit-to-xhtml.xslt" type="text/xsl"?>

<audit 
	xmlns="http://macaron.googlecode.com/1.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 	xsi:schemaLocation="http://macaron.googlecode.com/1.0/ http://macaron.googlecode.com/svn/trunk/audit/src/main/resources/com/googlecode/macaron/audit/audit.xsd"
	ignoreFilenames="^([^_]+_[a-z]{2}(_[A-Z]{2}(_[a-z]{1,3})?)?\.properties)|(.+\.(xsd|dtd|txt))$"
>

	<!-- Same package from differents jar. -->
	<packages>
		<package name="org/apache/">
			<context>jasper.jar</context>
			<context>catalina.jar</context>
		</package>
		<package name="org/apache/catalina/util/">
			<context>catalina-ant.jar</context>
			<context>catalina.jar</context>
		</package>
		<package name="org/apache/catalina/loader/">
			<context>bootstrap.jar</context>
			<context>catalina.jar</context>
		</package>
		<package name="org/apache/catalina/security/">
			<context>bootstrap.jar</context>
			<context>catalina.jar</context>
		</package>
		<package name="org/apache/catalina/startup/">
			<context>bootstrap.jar</context>
			<context>catalina.jar</context>
		</package>
		<package name="org/apache/naming/">
			<context>bootstrap.jar</context>
			<context>catalina.jar</context>
		</package>
	</packages>

	<!-- Same name with different package. -->
	<filenames>
		<filename name="LocalStrings.properties">
			<context>el-api.jar!javax/el/</context>
			<context>jasper.jar!org/apache/jasper/resources/</context>
			<context>catalina-tribes.jar!org/apache/catalina/tribes/</context>
			<context>tomcat-coyote.jar!org/apache/coyote/ajp/</context>
			<context>servlet-api.jar!javax/servlet/</context>
			<context>catalina.jar!org/apache/catalina/authenticator/</context>
			<context>catalina-ha.jar!org/apache/catalina/ha/</context>
		</filename>
		<filename name="mbeans-descriptors.xml">
			<context>jasper.jar!org/apache/jasper/servlet/</context>
			<context>catalina-tribes.jar!org/apache/catalina/tribes/</context>
			<context>tomcat-coyote.jar!org/apache/jk/</context>
			<context>catalina.jar!org/apache/catalina/authenticator/</context>
			<context>catalina-ha.jar!org/apache/catalina/ha/authenticator/</context>
		</filename>
		<filename name="catalina.properties">
			<context>bootstrap.jar!org/apache/catalina/startup/</context>
			<context>catalina.jar!org/apache/catalina/startup/</context>
		</filename>
	</filenames>

	<!-- Same basename with differents extensions in same package. -->
	<basenames/>

	<!-- Services in jar. -->
	<services/>
</audit>

=== pprados/macaron/seal/src/test/tomcat-ignore.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet href="audit.xslt" type="text/xsl"?>


<!-- 
 * Copyright 2009 Philippe Prados.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
-->

<audit 
	xmlns="http://macaron.googlecode.com/1.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://macaron.googlecode.com/1.0/versions%20tools/xsd/audit.xsd"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"	
	ignoreFilenames="^[^_]+_[a-z]{2}(_[A-Z]{2}(_[a-z]{1,3})?)?\.properties$"
>
	<!-- Meme package, archives diffÃ©rentes -->
	<packages>
		<package name="META-INF/"/>
		<package name="org/apache/catalina/loader/"/>
		<package name="org/apache/catalina/security/"/>
		<package name="org/apache/catalina/startup/"/>
		<package name="org/apache/catalina/util/"/>
		<package name="org/apache/naming/"/>
	</packages>
	
</audit>
